package dev.berikai.BitwigTheme.UI;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import dev.berikai.BitwigTheme.Main;
import dev.berikai.BitwigTheme.asm.JarNode;

import javax.swing.*;
import java.awt.*;
import java.util.zip.ZipException;

import static dev.berikai.BitwigTheme.Main.applyPatch;

public class Welcome extends JFrame {
    private JPanel mainPanel;
    private JButton letSGoButton;
    private JTextPane welcomeToBitwigThemeTextPane;

    public Welcome() {
        setContentPane(mainPanel);
        setTitle("Bitwig Theme Editor " + Main.version);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(430, 160);
        setLocationRelativeTo(null); // Center the window
        setResizable(false);

        letSGoButton.addActionListener(e -> {
            selectJar(this);
            setVisible(false);
            dispose();
        });

        setVisible(true);
    }

    public static void selectJar(Component parent) {
        JarChooser jarChooser = new JarChooser();
        String bitwig_path = jarChooser.getSelectedFile().getPath();

        // Create an ASM-tree JarNode object for bytecode manipulation
        try {
            Main.jar = new JarNode(bitwig_path);
        } catch (ZipException e) {
            String errorMessage = "Selected file " + bitwig_path + " is either invalid JAR file or corrupted.";
            JOptionPane.showMessageDialog(parent,
                    errorMessage,
                    "Error!",
                    JOptionPane.INFORMATION_MESSAGE);
            System.out.println("ERROR: JAR file " + bitwig_path + " is not valid or corrupted.");
            System.out.println();
            throw new RuntimeException(e);
        } catch (Exception e) {
            String errorMessage = "JAR File " + bitwig_path + " does not exist or could not be accessed. Try to run as admin/root.";
            JOptionPane.showMessageDialog(parent,
                    errorMessage,
                    "Error!",
                    JOptionPane.INFORMATION_MESSAGE);
            System.out.println("ERROR: JAR file " + bitwig_path + " does not exist or could not be accessed. Try to run as admin/root.");
            System.out.println();
            throw new RuntimeException(e);
        }

        // Patch jar
        // 1 = success, 0 = fail
        final int result = applyPatch(bitwig_path, Main.jar);
        new Editor(bitwig_path, result);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(2, 1, new Insets(10, 10, 10, 10), -1, -1));
        letSGoButton = new JButton();
        letSGoButton.setText("Select bitwig.jar");
        mainPanel.add(letSGoButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        welcomeToBitwigThemeTextPane = new JTextPane();
        welcomeToBitwigThemeTextPane.setEditable(false);
        welcomeToBitwigThemeTextPane.setEnabled(true);
        welcomeToBitwigThemeTextPane.setText("Welcome to Bitwig Theme Editor!\n\nSelect the bitwig.jar of your Bitwig Studio installation to get started.");
        mainPanel.add(welcomeToBitwigThemeTextPane, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
